require('dotenv').config()
const express = require('express')
const cors = require('cors')
const authRoutes = require('./routes/authRoutes')
const auctionRoutes = require('./routes/auctionRoutes')
const bidRoutes = require('./routes/bidRoutes')
const userRoutes = require('./routes/userRoutes')
const paymentRoutes = require('./routes/paymentRoutes')
const shippingRoutes = require('./routes/shippingRoutes')
const { errorHandler } = require('./middleware/errorHandler')

const app = express()
app.use(cors({ origin: process.env.FRONTEND_URL || 'http://localhost:3000' }))
app.use(express.json())
app.use('/uploads', express.static('src/uploads'))
app.use('/api/auth', authRoutes)
app.use('/api/auctions', auctionRoutes)
app.use('/api/bids', bidRoutes)
app.use('/api/users', userRoutes)
app.use('/api/payments', paymentRoutes)
app.use('/api/shipping', shippingRoutes)
app.use(errorHandler)

module.exports = app
